---
- name: Update and install Apache on Ubuntu and copy index.html
  hosts: webservers
  become: true

  tasks:

    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    
    - name: Ensure Apache is enabled and running
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started
    
    - name: Copy index.html to Apache web root
      ansible.builtin.copy:
       src: index.html
       dest: /var/www/html/index.html
       owner: www-data
       group: www-data
       mode: '0644'
      
    - name: Restart Apache
      ansible.builtin.service:
       name: apache2
       state: restarted
